# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/attr_extras/all/attr_extras.rbi
#
# attr_extras-6.2.4

module AttrExtras
  def self.mixin; end
end
class AttrExtras::AttrInitialize
  def apply; end
  def initialize(klass, names, block); end
  def klass; end
  def names; end
  def validate_args(values, klass_params); end
  def validate_arity(provided_arity, klass); end
end
class AttrExtras::AttrInitialize::ParamsBuilder
  def default_values; end
  def hash_args; end
  def hash_args_names; end
  def hash_args_required; end
  def initialize(names); end
  def names; end
  def positional_args; end
  def remove_required_sign(name); end
end
class AttrExtras::AttrValue
  def apply; end
  def define_equals; end
  def define_hash_identity; end
  def define_readers; end
  def initialize(klass, *names); end
  def klass; end
  def names; end
end
module AttrExtras::AttrQuery
  def self.define_with_suffix(klass, suffix, *names); end
end
class AttrExtras::AttrImplement
  def apply; end
  def initialize(klass, names); end
end
module AttrExtras::Utils
  def self.flat_names(names); end
end
class AttrExtras::MethodNotImplementedError < Exception
end
module AttrExtras::Mixin
  def aattr_initialize(*names, &block); end
  def attr_accessor_initialize(*names, &block); end
  def attr_id_query(*names); end
  def attr_implement(*names); end
  def attr_initialize(*names, &block); end
  def attr_private(*names); end
  def attr_private_initialize(*names, &block); end
  def attr_query(*names); end
  def attr_reader_initialize(*names, &block); end
  def attr_value(*names); end
  def attr_value_initialize(*names, &block); end
  def cattr_implement(*names); end
  def method_object(*names); end
  def pattr_initialize(*names, &block); end
  def rattr_initialize(*names, &block); end
  def static_facade(method_name_or_names, *names); end
  def vattr_initialize(*names, &block); end
end
class Module
  include AttrExtras::Mixin
end
