# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/cocina-models/all/cocina-models.rbi
#
# cocina-models-0.43.0

module Cocina
end
module Cocina::Models
  def self.build(dyn, validate: nil); end
  def self.build_request(dyn, validate: nil); end
end
class CocinaModelsInflector < Zeitwerk::Inflector
  def camelize(basename, _abspath); end
end
class Cocina::Models::Error < StandardError
end
class Cocina::Models::UnknownTypeError < Cocina::Models::Error
end
class Cocina::Models::ValidationError < Cocina::Models::Error
end
class Cocina::Models::Struct < Dry::Struct
  extend Dry::Core::DescendantsTracker
end
module Cocina::Models::Types
  extend Anonymous_Dry_Core_Deprecations_Tagged_51
  extend Anonymous_Module_52
  extend Dry::Core::Deprecations::Interface
  extend Dry::Types::BuilderMethods
  include Anonymous_Dry_Types_Module_53
end
module Cocina::Models::Types::Definition
end
module Anonymous_Dry_Types_Module_53
  def self.included(base); end
  extend Dry::Types::BuilderMethods
end
module Anonymous_Dry_Core_Deprecations_Tagged_51
end
module Anonymous_Module_52
  def const_missing(missing); end
end
