# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/datacite/all/datacite.rbi
#
# datacite-0.1.1

module Datacite
end
class Datacite::Error < StandardError
end
