# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/sorted_set/all/sorted_set.rbi
#
# sorted_set-1.0.3

class SortedSet < Set
  def initialize(*args); end
end
