# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/state_machines-activerecord/all/state_machines-activerecord.rbi
#
# state_machines-activerecord-0.6.0

module StateMachines
end
module StateMachines::Integrations
end
module StateMachines::Integrations::ActiveRecord
  def around_save(object); end
  def attribute_column; end
  def create_scope(name, scope); end
  def create_with_scope(name); end
  def create_without_scope(name); end
  def define_action_hook; end
  def define_state_initializer; end
  def locale_path; end
  def owner_class_ancestor_has_method?(scope, method); end
  def owner_class_attribute_default; end
  def runs_validations_on_action?; end
  def self.matching_ancestors; end
  def transaction(object); end
  extend StateMachines::Integrations::Base::ClassMethods
  include StateMachines::Integrations::ActiveModel
  include StateMachines::Integrations::Base
end
