# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/state_machines-graphviz/all/state_machines-graphviz.rbi
#
# state_machines-graphviz-0.0.2

module StateMachines
end
class StateMachines::Machine
end
class StateMachines::State
end
class StateMachines::Event
end
class StateMachines::Branch
end
class StateMachines::Graph < GraphViz
  def add_edges(*args); end
  def add_nodes(*args); end
  def file_format; end
  def file_path; end
  def font; end
  def initialize(name, options = nil); end
  def output; end
end
module StateMachines::Graphviz
end
class StateMachines::Railtie < Rails::Railtie
end
