# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/stimulus-rails/all/stimulus-rails.rbi
#
# stimulus-rails-0.1.2

module Stimulus
end
module Stimulus::ImportmapHelper
  def importmap_list_from(*paths); end
  def importmap_list_with_stimulus_from(*paths); end
  def importmap_module_name_from(filename); end
end
class Stimulus::Engine < Rails::Engine
end
module Stimulus::StimulusHelper
  def stimulus_include_tags; end
end
