# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/super_diff/all/super_diff.rbi
#
# super_diff-0.6.0

module SuperDiff
  def self.configuration; end
  def self.configure; end
  def self.time_like?(value); end
end
