# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: false
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/time/all/time.rbi
#
# time-0.1.0

class Time
  def httpdate; end
  def iso8601(fraction_digits = nil); end
  def rfc2822; end
  def rfc822; end
  def self.apply_offset(year, mon, day, hour, min, sec, off); end
  def self.force_zone!(t, zone, offset = nil); end
  def self.httpdate(date); end
  def self.iso8601(date); end
  def self.make_time(date, year, yday, mon, day, hour, min, sec, sec_fraction, zone, now); end
  def self.month_days(y, m); end
  def self.parse(date, now = nil); end
  def self.rfc2822(date); end
  def self.rfc822(date); end
  def self.strptime(date, format, now = nil); end
  def self.xmlschema(date); end
  def self.zone_offset(zone, year = nil); end
  def self.zone_utc?(zone); end
  def xmlschema(fraction_digits = nil); end
end
