# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: false
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/timeout/all/timeout.rbi
#
# timeout-0.1.1

module Timeout
  def self.timeout(sec, klass = nil, message = nil); end
  def timeout(sec, klass = nil, message = nil); end
end
class Timeout::Error < RuntimeError
  def exception(*arg0); end
  def self.catch(*args); end
  def thread; end
end
class Object < BasicObject
  def timeout(*args, &block); end
end
