# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strict
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/zipline/all/zipline.rbi
#
# zipline-1.3.0

module Zipline
  def zipline(files, zipname = nil); end
end
class Zipline::ZipGenerator
  def each(&block); end
  def handle_file(streamer, file, name, options); end
  def initialize(files); end
  def is_active_storage_attachment?(file); end
  def is_active_storage_one?(file); end
  def is_io?(io_ish); end
  def is_url?(url); end
  def normalize(file); end
  def to_s; end
  def write_file(streamer, file, name, options); end
end
