services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    environment:
      DATABASE_NAME: h2
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOSTNAME: db
      RAILS_LOG_TO_STDOUT: "true"
      REDIS_URL: redis://redis:6379/ # for ActionCable
      REMOTE_USER: sdr.user@stanford.edu
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis
      - workers
  workers:
    build:
      context: .
      dockerfile: docker/workers/Dockerfile
    environment:
      DATABASE_NAME: h2
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOSTNAME: db
      REDIS_URL: redis://redis:6379/ # for Sidekiq
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - db
      - redis
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: h2
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
  redis:
    image: redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
volumes:
  postgres-data:
  redis-data:
