# typed: strong
# This is an autogenerated file for Rails' mailers.
# Please rerun bundle exec rake rails_rbi:mailers to regenerate.
class HelpsMailer
  sig { params(email: T.untyped, subject: T.untyped, body: T.untyped).returns(ActionMailer::MessageDelivery) }
  def self.send_jira(email, subject, body); end
end
