# typed: strong
# This is an autogenerated file for Rails' mailers.
# Please rerun bundle exec rake rails_rbi:mailers to regenerate.
class HelpsMailer
  sig { returns(ActionMailer::MessageDelivery) }
  def self.jira_email; end
end
