# typed: strong
# This is an autogenerated file for Rails' mailers.
# Please rerun bundle exec rake rails_rbi:mailers to regenerate.
class NotificationMailer
  sig { returns(ActionMailer::MessageDelivery) }
  def self.reject_email; end
end
