# typed: strong
# This is an autogenerated file for Rails' mailers.
# Please rerun bundle exec rake rails_rbi:mailers to regenerate.
class ReviewersMailer
  sig { returns(ActionMailer::MessageDelivery) }
  def self.submitted_email; end
end
