#!/bin/bash

# This script runs as part of weekly dependency updates, making use of a new
# hooks system to allow for app-specific update behavior without changing the
# central auto-update infrastructure.
#
# See:
# https://github.com/sul-dlss/access-update-scripts/blob/81d786378c37b547486e83d174dbbb7e3c93e277/autupdate.sh#L34

# Database service must be running and DB must be created to allow sorbet-rails to generate RBIs
docker-compose up -d db
bundle install
bundle exec rails db:create db:migrate db:seed
SRB_YES=1 bundle exec srb rbi update
docker-compose down -v
git add sorbet && git commit -m 'Update type-checking signatures'
