#!/bin/bash

# This script runs as part of weekly dependency updates, making use of a new
# hooks system to allow for app-specific update behavior without changing the
# central auto-update infrastructure.
#
# See:
# https://github.com/sul-dlss/access-update-scripts/blob/81d786378c37b547486e83d174dbbb7e3c93e277/autupdate.sh#L34

# Else: Couldn't connect to Docker daemon at http+docker://localhost - is it running?
export DOCKER_HOST=unix:///var/run/docker.sock
env
echo $DOCKER_HOST
whoami
groups
pwd
docker info
docker ps
# Database service must be running and DB must be created to allow sorbet-rails to generate RBIs
docker-compose up -d db
bin/bundle install
bin/rails db:setup
SRB_YES=1 bin/bundle exec srb rbi update
bin/bundle exec rake rails_rbi:all
bin/bundle exec srb rbi hidden-definitions
bin/bundle exec srb rbi suggest-typed
docker-compose down
git add sorbet && git commit -m 'Update type-checking signatures'
